(function(){
'use strict';const S=window.ContactSchema,U=window.StoreUI,$=id=>document.getElementById(id);let draft=S.normalize(S.defaults),version=0,loaded=false,busy=false,dirty=false;
const status=t=>$('contactStatus').textContent=t;
function lock(v){busy=v;for(const el of $('contactsTab').querySelectorAll('input,textarea,button'))el.disabled=v||(!loaded&&el.id!=='contactReload');}
function draw(){const box=$('contactFields');box.replaceChildren();for(const [store,title]of [['embroidery','ATHNTA · التطريز'],['printing','LAVINTA · الطباعة']]){
 const panel=U.node('article','panel'),heading=U.node('h2','',title);panel.append(heading);
 for(const [key,label]of Object.entries(S.channels)){const row=U.node('div','contact-row'),text=U.node('label','',label),input=U.node('input');input.type=key==='email'?'email':'text';input.dir='ltr';input.value=draft[store][key].value;input.placeholder=['phone','whatsapp'].includes(key)?'96655XXXXXXX':key==='email'?'name@example.com':'https://';text.append(input);const show=U.node('label','contact-show'),check=U.node('input');check.type='checkbox';check.checked=draft[store][key].enabled;show.append(check,document.createTextNode('إظهار'));const preview=U.node('a','quiet-link','تجربة ↗');preview.target='_blank';preview.rel='noopener noreferrer';
 const update=()=>{try{const url=S.href(key,{enabled:true,value:input.value});if(url){preview.href=url;preview.hidden=false;}else{preview.removeAttribute('href');preview.hidden=true;}}catch{preview.removeAttribute('href');preview.hidden=true;}};
 input.addEventListener('input',()=>{draft[store][key].value=input.value;dirty=true;update();status('تغييرات غير محفوظة');});check.addEventListener('change',()=>{draft[store][key].enabled=check.checked;dirty=true;status('تغييرات غير محفوظة');});update();row.append(text,show,preview);panel.append(row);}
 const label=U.node('label','','رسالة واتساب العامة'),message=U.node('textarea');message.maxLength=500;message.value=draft[store].message;message.addEventListener('input',()=>{draft[store].message=message.value;dirty=true;status('تغييرات غير محفوظة');});label.append(message);panel.append(label);box.append(panel);
 }lock(false);}
 async function request(method,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const token=await window.athntaAuth.currentUser.getIdToken();const r=await fetch('/api/contacts',{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الاتصال');return d;}finally{clearTimeout(timer);}}
 async function load(){if(busy||!window.themeAdminReady)return;if(dirty&&!confirm('إلغاء التغييرات غير المحفوظة وإعادة التحميل؟'))return;lock(true);try{const d=await request('GET');draft=S.normalize(d.contacts);version=d.version;loaded=true;dirty=false;draw();status('تم تحميل الروابط المحفوظة');}catch(e){status(e.name==='AbortError'?'انتهت مهلة الاتصال':e.message);}finally{lock(false);}}
 $('contactSave').addEventListener('click',async()=>{if(busy||!loaded||!window.themeAdminReady)return;let clean;try{clean=S.normalize(draft,true);}catch(e){status(e.message);return;}lock(true);try{const d=await request('POST',{contacts:clean,version});draft=S.normalize(d.contacts);version=d.version;dirty=false;draw();status('تم حفظ روابط المتجرين. تظهر عند تحديث المعرض.');}catch(e){status(e.name==='AbortError'?'انتهت مهلة الاتصال؛ أعد تحميل المحفوظ للتحقق قبل إعادة الحفظ':e.message);}finally{lock(false);}});
 $('contactReload').addEventListener('click',load);$('btnContactsTab').addEventListener('click',e=>{window.switchTab(e,'contactsTab');if(!loaded)load();});window.addEventListener('theme-admin-ready',()=>{if(document.body.dataset.adminTab==='contactsTab'&&!loaded)load();});window.addEventListener('admin-signed-out',()=>{loaded=false;lock(false);});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});draw();
})();
